---
title: "Understanding Trading Patterns"
subtitle: "For Top 3 Trading Economies"
author: 'Prachi Jaiswal, Sithalakshmi Jawahar, Yuwei Jiang'
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
    bookdown::html_document2
keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = TRUE)
```

```{r , echo = FALSE}
library(readr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(plotly)
library(kableExtra)
library(ggpubr)
library(gridExtra)
library(grid)
```

```{r, echo = FALSE}

clean <- function(x, y) {
  read.csv(x) %>% 
  select(Country.or.Area: Trade..USD.) %>% 
  rename( Country = "Country.or.Area", Trade ="Trade..USD." ) %>% 
  mutate(Category = factor(y)) %>% 
  select(-Commodity)
}


iron_steel <- clean("data/UNdata_Export_20210520_091706592.csv", "iron_steel")
fruits_nuts <- clean("data/UNdata_Export_20210520_092512505.csv", "fruits_nuts")
rubber <- clean("data/UNdata_Export_20210520_092039303.csv", "rubber")
cars <- clean("data/UNdata_Export_20210519_132226922.csv","cars")
coffee <- clean("data/UNdata_Export_20210519_133347537.csv","coffee")
cotton <- clean("data/UNdata_Export_20210519_132629219.csv","cotton")
pharma <- clean("data/UNdata_Export_20210519_132341600.csv","pharma")
sugar <- clean("data/UNdata_Export_20210519_132821334.csv","sugar")
tobacco <- clean("data/UNdata_Export_20210519_131835858.csv","tobacco")
wheat <- clean("data/UNdata_Export_20210519_132931178.csv","wheat")

```

```{r, echo = FALSE}
team_nemo<- rbind(iron_steel, fruits_nuts, rubber, cars, coffee, cotton, pharma, sugar, tobacco, wheat)
final <- write_csv(team_nemo, "data/team_nemo.csv")

```


\section*{Introduction}


\section*{Germany}
```{r pread, echo=FALSE}
germany_import <- final %>% filter(Country == "Germany", Flow == "Import")
germany_export <- final %>% filter(Country == "Germany", Flow == "Export")
```

```{r pgraph, echo=FALSE, fig.cap = "Trade value of Goods in Germany", out.width = "150%"}

graph <- function(a, b)
  {  
    a %>%
    ggplot(aes(Category, Trade, fill = Category))+
    geom_col()+
    scale_y_continuous(labels=scales::dollar_format())+
    
    facet_grid(~Year)+
    theme_dark()+
    scale_fill_brewer(palette = "Set3")+
    
    ylab("Trade in USD")+
    xlab(b)+
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
  }


gi<- graph(germany_import, "Import Goods")
ge<- graph(germany_export, "Export Goods") 

ggarrange(gi, ge, 
          common.legend = TRUE, legend = "top",
          ncol =1, nrow = 2)
```



\section*{China}


\section*{USA}


\section*{Conclusion}


